from __future__ import annotations

AI_HTTP_TIMEOUT_TOTAL: float = 120.0
AI_HTTP_TIMEOUT_CONNECT: float = 30.0

AI_MAX_RETRIES: int = 3
AI_BASE_DELAY: float = 5.0

AI_TEMPERATURE_DEFAULT: float = 0.3
AI_TEMPERATURE_SEGMENTATION: float = 0.1
AI_TEMPERATURE_PROOFREADING: float = 0.2
AI_TEMPERATURE_LANGUAGE_DETECT: float = 0.0
AI_MAX_TOKENS_DEFAULT: int = 4096
AI_MAX_TOKENS_LANGUAGE_DETECT: int = 10

AI_SEGMENTATION_MAX_WORDS: int = 18
AI_SEGMENTATION_MIN_WORDS: int = 5
AI_SEGMENTATION_MAX_ATTEMPTS: int = 3

AI_TRANSLATION_BATCH_SIZE: int = 45
AI_TRANSLATION_MAX_WORDS: int = 18
AI_TRANSLATION_MIN_WORDS: int = 5
AI_TRANSLATION_MAX_ATTEMPTS: int = 3

AI_PROOFREADING_BATCH_SIZE: int = 20
AI_PROOFREADING_CONTEXT_SIZE: int = 3

AI_LANGUAGE_DETECT_SAMPLE_LENGTH: int = 2000

SUBTITLE_ASS_RESOLUTION_X: int = 1920
SUBTITLE_ASS_RESOLUTION_Y: int = 1080

SUBTITLE_ASS_FONT_SIZE_PRIMARY: int = 58
SUBTITLE_ASS_FONT_SIZE_SECONDARY: int = 38

SUBTITLE_ASS_MARGIN_LEFT: int = 30
SUBTITLE_ASS_MARGIN_RIGHT: int = 30
SUBTITLE_ASS_MARGIN_VERTICAL: int = 35

SUBTITLE_ASS_COLOR_PRIMARY: str = "&H00FFFFFF"
SUBTITLE_ASS_COLOR_SECONDARY: str = "&H00FFFFFF"
SUBTITLE_ASS_COLOR_OUTLINE: str = "&H000000FF"
SUBTITLE_ASS_COLOR_BACK: str = "&H00000000"
SUBTITLE_ASS_COLOR_SHADOW: str = "&H80000000"

SUBTITLE_ASS_OUTLINE_WIDTH: int = 3
SUBTITLE_ASS_SHADOW_DEPTH: int = 0

SUBTITLE_TIME_GAP_MS: int = 10
SUBTITLE_END_EXTENSION_MS: int = 2000
SUBTITLE_MIN_DURATION_MS: int = 1000

SUBTITLE_LANG_DETECT_THRESHOLD_LATIN: float = 0.7
SUBTITLE_LANG_DETECT_THRESHOLD_CJK: float = 0.3
SUBTITLE_LANG_DETECT_THRESHOLD_JAPANESE: float = 0.1
SUBTITLE_LANG_DETECT_THRESHOLD_MIXED: float = 0.05

DOWNLOADER_ANSI_ESCAPE_PATTERN: str = r"\033\[[0-9;]*m"
DOWNLOADER_YOUTUBE_VIDEO_ID_LENGTH: int = 11
DOWNLOADER_YOUTUBE_URL_PATTERNS: list[str] = [
    r"youtube\.com/watch\?v=([a-zA-Z0-9_-]{11})",
    r"youtu\.be/([a-zA-Z0-9_-]{11})",
    r"youtube\.com/embed/([a-zA-Z0-9_-]{11})",
    r"youtube\.com/v/([a-zA-Z0-9_-]{11})",
    r"youtube\.com/shorts/([a-zA-Z0-9_-]{11})",
]

FFMPEG_FFPROBE_TIMEOUT_S: int = 30
FFMPEG_FFMPEG_TIMEOUT_S: int = 600
FFMPEG_ERROR_TRUNCATE_LENGTH: int = 500
